# Generated by Django 5.1.4 on 2024-12-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_usuarioerp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioERP',
        ),
    ]
