# Generated by Django 5.1.4 on 2024-12-14 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_delete_usuarioerp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveisAcesso',
            fields=[
                ('nivel_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('nivel_acesso', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Ativo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecuperacaoSenha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_recuperacao', models.CharField(max_length=6)),
                ('data_pedido', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('coluna_alterada', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_antigo', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioNivelAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.niveisacesso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.usuarios')),
            ],
            options={
                'unique_together': {('usuario', 'nivel_acesso')},
            },
        ),
    ]
